### ISSUE TITLE
Playback stops altogether when buffer fails

### ISSUE THREAD

**Issue by Porco-Rosso** [SubmarinerApp/Submariner#139]
**Describe the bug**
When listening to songs, sometimes the playback stops all-together. Only starting to play another song resumes playback.
When playback fails, the song timer keeps counting up. 
I assume this is a problem with the buffer not keeping up due to server bandwidth issues. Something might be wrong with how the player recovers from the playback.
Pausing and resuming playback doesn't fix the issue.
This doesn't happen when I stream directly from the Navidrome webUI

This happens much more often with longer songs, such as mixtapes.
[Submariner cache fail.txt](https://github.com/SubmarinerApp/Submariner/files/11847258/Submariner.cache.fail.txt)
Here is the console log. Playback fails at the last line: `<<<< FAQ TIMING SHIM >>>> FigAudioQueueTimingShimFlush: [0x600001e19ef0] Calling AudioQueueFlush(0x1140219d)`

**To Reproduce**
1. Play song from Navidrome that is long (20m+)
2. After ~1M playback stops, but the song timer keeps counting up, as if playing.
3. pause/start does not fix playback

**Expected behavior**
Player pauses for buffer and then resumes gracefully

**Screenshots**
Not sure it would help. 

**Versions:**
- macOS 13.1
- Navidrome [0.49.3](https://github.com/navidrome/navidrome/releases/tag/v0.49.3)
- Download Source: github v2.3

**Additional context**
None.

**Comment by NattyNarwhal** [comment]
I have a suspicion this might be related to [AVURLAssetPreferPreciseDurationAndTimingKey](https://developer.apple.com/documentation/avfoundation/avurlassetpreferprecisedurationandtimingkey?language=objc), without it, FLAC seeking and elapsed times can be inaccurate. Is the media you're trying to play FLAC?

I also wonder if it might be related to automatic downloads when starting playback, and the network traffic caused by that on the same server messing with the live stream happening. Do you have that option on, and are you playing tracks that aren't downloaded/have a downloaded version?

**Comment by NattyNarwhal** [comment]
For the latter case, I don't think the current mechanism for this is terribly clear about its intent or when it's supposed to trigger, so I'm refactoring it there. It should now do it before track start.

**Comment by Porco-Rosso** [comment]
I'm playing 320kbps Mp3s, no fancy FLACs.
Also not downloading anything, just streaming the content. 

The bandwidth to my server should be okay, I get 6-7Mbs on other transfers.

**Comment by NattyNarwhal** [comment]
If you're not using downloads (automatic or otherwise), then my suspicion is the precise seeking/timing option causing problems. I've made another test build, including a change that will only set that option for FLACs and the changes to automatic download behaviour.

[Submariner-2.3.zip](https://github.com/SubmarinerApp/Submariner/files/11858540/Submariner-2.3.zip)

**Comment by Porco-Rosso** [comment]
Sorry I was traveling and didn't have time to test. So far it seems to have fixed the problem. Thanks!
