### ISSUE TITLE
Subsonic Error (code 70) / Requested action getNowPlaying is not supported

### ISSUE THREAD

**Issue by dawe-rgb** [SubmarinerApp/Submariner#148]
**Describe the bug**
When I click on an artist and the albums of that artist are displayed, the error message is displayed for each album: 

Subsonic Error (code 70)
Requested action getNowPlaying is not supported

**To Reproduce**
1. Go to 'Added Subsonic Server'
2. Click on 'Artists'
3. See the error message per album

**Expected behavior**
No Error PopUp-Message

**Screenshots**
<img width="372" alt="Bildschirmfoto 2023-07-27 um 16 11 44" src="https://github.com/SubmarinerApp/Submariner/assets/56391227/71db23c8-8317-4beb-9c56-ff4d65e29574">

**Versions:**
 - macOS [e.g. 13.5]: 13.4.1 (c)
 - Subsonic Server and Version [e.g. Navidrome 0.44, Subsonic 6.1.6]: Nextcloud 27.0.1, With Music v1.8.4 Plugin:  (https://github.com/owncloud/music/releases/tag/v1.8.4)
 - Submariner Version [e.g. 2.2]: 2.3.1
 - Download Source [e.g. Mac App Store]: Mac App Store

**Additional context**

**Comment by NattyNarwhal** [comment]
Looks like Nextcloud Music doesn't support the "now playing" functionality (that shows what other users are listening to). It's not a big deal since it *should* only be touching that endpoint if the now playing sidebar is activated (even if hidden) though. However, there *is* an auto-refresh timer for it. Disabling that timer in the settings might help with this.

Unfortunately, there is no way to check for featureset beyond Subsonic API version numbers. It's a bit annoying to support multiple servers as a result.

<img width="472" alt="Screenshot 2023-07-27 at 3 37 37 PM" src="https://github.com/SubmarinerApp/Submariner/assets/3161292/6c5e86f1-ed3e-42db-bfc2-e6d743b8c6f5">

**Comment by dawe-rgb** [comment]
Thanks for your reply. I see, unfortunately it doesn't help to disable the Auto Refresh from Now Playing. The now playing sidebar is closed. Is there any way not to display the error message in this case? Or e.g. display "not availible with the curret server" in the sidebar? Submariner is really a great app and I use it despite the error message, although it is annoying. :-)

**Comment by NattyNarwhal** [comment]
Looking at the callsites, it *does* call now playing on each refresh (i.e. via Cmd+R).

Annoyingly, code 70 is also used for when the API exists but the requested object wasn't found. We'd have to keep track of what APIs returned code 70, and check what didn't work at each part that calls it, basically. This is more annoying than being able to just check if it wouldn't work from the beginning, but it'd work.

**Comment by dawe-rgb** [comment]
When I press Cmd+R, the error message 70 appears.

**Comment by sbkg0002** [comment]
On a newly installed submariner + clean subsonic installation, I have the same issue.

**Comment by NattyNarwhal** [comment]
I just got back from vacation, so I can take a look at this again.

**Comment by dawe-rgb** [comment]
I have just tried a few old versions. The problem appears from version 2.2 onwards. Version 2.1.1 runs without the error message code "Subsonic Error (code 70) / Requested action getNowPlaying is not supported". Might this help?

**Comment by NattyNarwhal** [comment]
2.2 introduced [refreshing the now playing view as part of refreshing normally](https://github.com/SubmarinerApp/Submariner/commit/8b17f416a1c74ea0440879e3f461dfe41ca0b46b#diff-5c2840864d6a69bd299725cb010f71d8e0482ffc90314d0649ccac1290b70012R656).

FWIW, I've filed owncloud/music#1079 as a server-side solution for OC Music at least. On the Submariner side, it's a little bit annoying because servers can return different things for unimplemented routes - i.e. OC Music returns code 70 Subsonic responses, whereas Navidrome returns HTTP 404s.

**Comment by NattyNarwhal** [comment]
Fixed this, will be available in the next release

**Comment by dawe-rgb** [comment]
Thanks for the fix! I'm already looking forward to the new release :)
