### ISSUE TITLE
Server reporting "Unvalid license" even though it's connected successfully

### ISSUE THREAD

**Issue by GetOutOfMyBakery** [SubmarinerApp/Submariner#160]
# What
Last follow on from [this comment](https://github.com/SubmarinerApp/Submariner/issues/157#issuecomment-1686687340).
When I've created a server connection on 2.4, I'm now seeing `Unvalid License` in when I go to `Configure Server` on a successfully connected server. My previous server connection (from 2.3.1 did not have this message).

I noticed this on my other (work) Mac, so came to check it on my own Mac which had been successfully connected on a previous build (2.3.1). I reproduced the issue when connecting to the same server on 2.4. Both times the indicator was green.

I also had a little dig through the code and it looked like it's associated to the presence/absence of an email address for the user account (I might be wrong on this), so I gave my Navidrome user a temporary email address, and re-connected. This didn't seem to resolve the issue though.

# Steps to reproduce
1. Connect to a new valid server on Submariner 2.4
1. Click `Configure Server`, and see if you have a successful connection

## Screenshots
<img width="379" alt="image" src="https://github.com/SubmarinerApp/Submariner/assets/12701930/fbea3595-5e2b-4305-b1bc-60806c2c778e">

## Versions
- Navidrome `0.49.3 (8b93962f)`
- Submariner 2.4 (installed via `brew`)

**Comment by NattyNarwhal** [comment]
It's because Navidrome doesn't return any license info in `getLicense`:

```xml
<subsonic-response xmlns="http://subsonic.org/restapi" status="ok" version="1.16.1" type="navidrome" serverVersion="0.40.0-FREEBSD (8799358)"><license valid="true"></license></subsonic-response>
```

...and the default license 

![Screenshot 2023-08-21 at 10 53 02 PM](https://github.com/SubmarinerApp/Submariner/assets/3161292/4d46c23f-3f4d-4c02-8796-73a8a60fbf37)

It's purely cosmetic, the `ok` in there means that the valid license bit is set, making the light there green. Submariner and Navidrome don't actually do anything with license information, but Subsonic does care.
