### ISSUE TITLE
Feature request: View by folder (and other options)

### ISSUE THREAD

**Issue by tcryuvgbhjkl** [SubmarinerApp/Submariner#173]
Currently Submariner allows to view by Artist, Album and Podcast. Would it be possible to add more views? In my case specifically interested by folder view since the folders are organized but id3 tags are a mess.

**Comment by NattyNarwhal** [comment]
Unfortunately, Submariner right now is actually doing the worst of both worlds and beating the folder based view into an artist-album-track hierarchy. This is OK for things like Navidrome that basically make up a fake directory hierarchy based on tags (which is really funny, because Submariner predates Navidrome by a lot), but it's not so good for Subsonic, which presents the actual filesystem view.

An issue to get us onto the ID3 based model that makes more sense for Subsonic is GH-73, but I'm keeping this as filesystem based browsing could be done too. It's mostly just ugly data model migration stuff; I hope I can do it without a flag day.

**Comment by NattyNarwhal** [comment]
This should be in the next release.
