### ISSUE TITLE
Mark currently playing song as favorited

### ISSUE THREAD

**Issue by Darksecond** [SubmarinerApp/Submariner#212]
**Is your feature request related to a problem? Please describe.**
I would like to be able to mark the currently playing song as a favorite.

**Describe the solution you'd like**
A menu toggle, maybe a button, and a keyboard shortcut to mark the currently playing song as favorite (heart)

**Additional context**
Unfortunately it's not possible to mark a track as favorite in the tracklist otherwise I could use that.

**Comment by NattyNarwhal** [comment]
Looking into adding a menu option, GH-199. I think I know how to do this in a way that's not ugly (because the menu and the view controllers aren't aware of each other's state).

As a workaround, you can use AppleScript: `tell application "Submariner" to set loved of current track to true`

Fun fact! The now playing controls on iOS and watchOS have a like/favourite button, but not on macOS. If the system now playing controls ever do expose this though, the command is already implemented.

**Comment by NattyNarwhal** [comment]
I've added a Favourite option in the menu for the selection in the next release. It has a shortcut on Cmd+E, so you could use Cmd+L for select current track, then Cmd+E for favouriting it. (This menu option also works from the tracklist.)
